name: city-lines-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.7
  - numpy
  - pandas
  - geopandas
  - matplotlib
  - scikit-image
  - colour-science
  - pymysql
  - sqlalchemy
  - doit
  - pip
  - pip:
    - -e .
    - mysql-connector-python