name: city-lines-env
channels:
  - defaults
dependencies:
  - python=3.9.7
  - pandas
  - matplotlib
  - geopandas
  - pymysql
  - sqlalchemy
  - doit
  - pip
  - pip:
    - -e .
    - mysql-connector-python